//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.h
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

@interface LHSettings : NSObject
{
	bool useRetinaOnIpad;
	float lhPtmRatio;
	float customAlpha; //used by SceneTester
	int newBodyId;
	CGPoint convertRatio;
    CGPoint realConvertRatio;
	bool convertLevel;
	
    bool stretchArt;
    CGPoint possitionOffset;
    bool levelPaused;
	//NSMutableString* imagesFolder;
    bool isCoronaUser;
    
    bool preloadBatchNodes;
}
@property bool useRetinaOnIpad;
@property float lhPtmRatio;
@property float customAlpha;
//@property CGPoint convertRatio;
@property bool convertLevel;
@property bool levelPaused;
@property bool isCoronaUser;
@property bool preloadBatchNodes;

+(LHSettings*) sharedInstance;

-(int)newBodyId;
//-(void) setImageFolder:(NSString*)img;
//-(NSString*)imageFolder;



-(NSString*)imagePath:(NSString*)file imageFolder:(NSString*)imagesFolder;
-(bool)shouldScaleImageOnRetina:(NSString*)image;
-(bool)isIpad;

-(void) setStretchArt:(bool)value;

-(CGPoint) possitionOffset;
-(void) setConvertRatio:(CGPoint)val usesCustomSize:(bool)usesCustomSize;
-(CGPoint) convertRatio;
-(CGPoint) realConvertRatio;
@end	
