//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.mm
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

#import "LHBatchExt.h"
#import "LHBatch.h"
@implementation LevelHelperLoader (BATCH_EXTENSION)
////////////////////////////////////////////////////////////////////////////////
-(CCSpriteBatchNode*) spriteBatchNodeForFile:(NSString*) imageName
{
    LHBatch* bnode = [batchNodesInLevel objectForKey:imageName];
    if(bnode != nil)
    {
        return [bnode spriteBatchNode];
    }
    return nil;
}
//-(void) deleteBatchNodeForFile:(NSString*)imageName
//{
//    CCSpriteBatchNode* cNode = [self spriteBatchNodeForFile:imageName];
//    
//    if(nil == cNode)
//        return;    
//
//    NSArray *keys = [spritesInLevel allKeys];
//    if(nil == keys)
//        return;
//    
//    
//    NSArray* parKeys = [parallaxesInLevel allKeys];
//    if(nil == parKeys)
//        return;
//        
//	for(NSString* key in keys)
//    {
//        LHSprite* spr = [self spriteWithUniqueName:key];
//
//        if(spr != nil)
//        {
//            if([spr batchNode] == cNode)
//            {
//                for(NSString* pKey in parKeys)
//                {
//                    LHParallaxNode* pNode = [self paralaxNodeWithUniqueName:pKey];
//                    [pNode removeChild:spr];
//                }
//                [self removeSprite:spr];
//            }
//        }
//	}	
//    
//    [batchNodesInLevel removeObjectForKey:imageName];
//}
////////////////////////////////////////////////////////////////////////////////
-(NSArray*) batchNodesInLevel
{
    NSArray* keys = [batchNodesInLevel allKeys];
#ifndef LH_ARC_ENABLED
    NSMutableArray* batches = [[[NSMutableArray alloc] init] autorelease];
#else
    NSMutableArray* batches = [[NSMutableArray alloc] init];
#endif
    for(NSString* img in keys)
    {
        LHBatch* bNode = [batchNodesInLevel objectForKey:img];
        
        if(bNode != nil)
        {
            [batches addObject:[bNode spriteBatchNode]];
        }
    }
    return batches;
}
////////////////////////////////////////////////////////////////////////////////
@end
