//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.mm
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

#import "LHCreationExt.h"
#import "LHSettings.h"
#import "LHBatch.h"
@implementation LevelHelperLoader (NEW)
////////////////////////////////////////////////////////////////////////////////
-(LHSprite*) newSpriteWithUniqueName:(NSString*)uniqueName 
						cocos2dLayer:(CCLayer*)_cocosLayer
{
    LHSprite* ccsprite = [self createSpriteWithUniqueName:uniqueName];
	if(nil != ccsprite)
        [_cocosLayer addChild:ccsprite];
    
    return ccsprite;
}
////////////////////////////////////////////////////////////////////////////////
//-(NSArray*)newSpritesWithTag:(enum LevelHelper_TAG)tag
//				cocos2dLayer:(CCLayer*)_cocosLayer
//{
//	NSMutableArray* array = [[[NSMutableArray alloc] init] autorelease];
//	for(NSDictionary* dictionary in lhSprites){
//		NSDictionary* spriteProp = [dictionary objectForKey:@"GeneralProperties"];
//		if((LevelHelper_TAG)[[spriteProp objectForKey:@"Tag"] intValue] == tag)
//		{
//                                                                
//			LHSprite* ccsprite = [self spriteFromDictionary:spriteProp];
//			
//			if(nil != ccsprite)
//			{
//				[array addObject:ccsprite];
//                
//                if(nil != _cocosLayer)
//                    [_cocosLayer addChild:ccsprite];
//			}
//		}
//	}
//	
//	return array;
//}




////////////////////////////////////////////////////////////////////////////////
-(b2Body*) newBodyWithUniqueName:(NSString*)name 
						   world:(b2World*)_world
{
    LHSprite* ccsprite = [self createPhysicalBatchSpriteWithUniqueName:name];
    if(nil != ccsprite){
        return [ccsprite body];
    }
	return 0;
}
////////////////////////////////////////////////////////////////////////////////
-(b2Body*) newBodyWithUniqueName:(NSString*)uniqueName 
						   world:(b2World*)_world
					cocos2dLayer:(CCLayer*)_cocosLayer
{
    LHSprite* ccsprite = [self createPhysicalSpriteWithUniqueName:uniqueName];
    
    if(nil != ccsprite){
        if(nil != _cocosLayer){
            [_cocosLayer addChild:ccsprite];
        }
        return [ccsprite body];    
    }
    return 0;
}
////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////////
//-(NSArray*) newBodiesWithTag:(enum LevelHelper_TAG)tag 
//                       world:(b2World*)_world
//                cocos2dLayer:(CCLayer*)_cocosLayer
//{
//	NSMutableArray* array = [[[NSMutableArray alloc] init] autorelease];
//	
//	for(NSDictionary* dictionary in lhSprites)
//	{
//		NSDictionary* spriteProp = [dictionary objectForKey:@"GeneralProperties"];
//		
//		if((LevelHelper_TAG)[[spriteProp objectForKey:@"Tag"] intValue] == tag)
//		{
//			LHSprite* ccsprite = [self spriteFromDictionary:spriteProp];
//			
//			if(nil != ccsprite)
//			{
//				NSDictionary* physicProp = [dictionary objectForKey:@"PhysicProperties"];
//			
//                b2Body* body = [self b2BodyFromDictionary:physicProp
//                                         spriteProperties:spriteProp
//                                                     data:ccsprite 
//                                                    world:_world];
//                
//                if(0 != body)
//                {
//                    [ccsprite setBody:body];
//
//                    NSValue* v = [NSValue valueWithPointer:body];
//                    [array addObject:v];
//				
//                    if(nil != _cocosLayer)
//                        [_cocosLayer addChild:ccsprite];
//                }
//			}
//		}
//	}
//	return array;
//}
@end
